реализованы тесты assert-rules
NurGeo/rilata2 pull request #1
Opened 2023-09-07 11:01 UTC by Renatter

2023-09-07 19:50 UTC, FredSteady23 approved these changes

2023-09-08 06:55 UTC, NurGeo requested changes

2023-09-08 06:55 UTC, NurGeo commented on tests/domain/validator/field/rules/assert-rules-test/cannot-be-empty-array.a-rule.test.ts
> +    test('success, received value equal array', () => {
received value not empty array

2023-09-08 06:55 UTC, NurGeo commented on tests/domain/validator/field/rules/assert-rules-test/cannot-be-empty-string.a-rule.test.ts
> +      });
прокрути через цикл со значениями: `['s', 'not empty', ' ', '0', ';']`;

2023-09-08 06:55 UTC, NurGeo commented on tests/domain/validator/field/rules/assert-rules-test/cannot-be-empty-array.a-rule.test.ts
> +  });
походу у тебя еще не работает esllint. тебе на самом деле нужно установить плагин eslint для vscode.

2023-09-12 11:38 UTC, closed without merging