Реализовал тесты field-validator для array
NurGeo/rilata2 pull request #19
Opened 2023-09-22 06:51 UTC by Renatter

2023-09-22 07:26 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +    const result = sut.validate([{ number: '+7-777-287-81-82', type: 'mobile', noOutField: 'empty info' }, { number: '+7-777-287-81-82', type: 'mobile', noOutField: 'empty info' }]);
1. `success, received many dto values`;
2. измени данные второго элемента, номер, тип,noOut;
3. напиши в формате: sut.validate([
   {obj1},
   {obj2},
 ]);

2023-09-22 07:26 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +  test('failure, The value must not be undefined or null', () => {
описание говорит что не должно быть undefined или null, а в проверку уходит пустой массив.
Что ты тут тестируешь?

2023-09-22 07:26 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +});
нужны тестовые случаи.
1. Тесты с настройками самого массива.
1.1 не обязательный массив.
- передали пустой массив
- передали валидный массив
- передали не валидный массив
- передали undefined
1.2 обязательный массив
- передали пустой массив
- передали валидный массив
- передали не валидный массив
- передали undefined
1.3 массив должен быть заполнен
- передали пустой массив
- передали не пустой массив с валидными значениями
- передали не пустой массив с не валидным значением
- передали undefined
1.4 массив должен иметь минимальное количество значений
- передали с валидными значениями с меньшим количеством элементов
- передали с валидными значениями с граничным количеством элементов
- передали с валидными значениями с большим количеством элементов
- передали undefined
1.5 то же самой что и 1.4, только для максимального количества значений.
2. Что валидация самих значений выполняется
2.1 Массивы с простым типом данных
- валидный массив
- массив где один из значений не валидный
2.2 то же самое что и 2.1, только для dto;

2023-09-28 06:18 UTC, FredSteady23 commented on tests/domain/validator/field/field-validatorArray.test.ts
> +//   const sut = FieldValidatorFixtures.contactAttrsValidatormap.phones;
Удали комменты, они не нужны в основной ветке

2023-09-28 07:10 UTC, NurGeo requested changes

2023-09-28 07:10 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +    const sut = FieldValidatorFixtures.contactAttrsValidatormap.phones;
сделай новый валидатор для простых значений, например:
```
const roles = ['admin', 'staffManager', 'officeChieff', 'saleManager'];
const sut = new LiteralFieldValidator('roles', 'string', true, {isArray: true, mustBeFilled: true}, [new StringChoiceRule(roles));
```

1. сделай такие же тесты которые ты делал выше для dtoValidatora делай для нее.
2. поставь эти тесты выше, потому что валидация данного массива проще и человеку будет проще входить в то как работает валидация массивов.

2023-09-28 07:31 UTC, FredSteady23 commented on tests/domain/validator/field/field-validatorArray.test.ts
> +import { FieldValidatorPrivateFixtures as FieldValidatorFixtures, FieldValidatorPrivateFixtures } from './test-fixtures';
FieldValidatorPrivateFixtures а зачем тут еще раз объявлять то что уже есть

2023-10-03 09:17 UTC, FredSteady23 approved these changes

2023-10-05 10:19 UTC, KLeBerLacky approved these changes

2023-10-05 13:41 UTC, NurGeo approved these changes
Ставлю апрув, чтобы не потом смотреть. Потом перед коммитом мне покажи что изменил и как.

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +          return [new CannotBeUndefinedValidationRule(), new CanBeNullValidationRule()];
я вижу что ты не используешь тернарный оператор и проверкой isRequired. Как прочитаешь объясни мне устно, почему это не обязательно делать? Или все таки надо делать?

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +      const res = sut.validate(1);
вместо 1, 'admin'

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +    describe('validate value is requied but not null', () => {
скорее всего: `значение не обязательно, но  null невалидное значение`

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +describe('dto_tests', () => {
написать описание нормальным языком, ниже тоже

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +      const result = sut.validate(1);
отправить валидный dto, но не массив

в тестах всегда моделируйте максимально похожее на реальное выполнение поведение (ситуацию)

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +        { number: '+7-777-287-81-82', type: 1, noOutField: 'empty info' },
лучше бы какую нибудь строку, например "home"

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +        ___whole_value_validation_error___: {
___whole_value_validation_error___: {

как думаешь, правильно???

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +        { number: '85-777-287-81-82', type: 1, noOutField: 'empty info' },
1. тоже самое с 1
2. прочитай повнимательнее описание, ты не этот тестовый случай делаешь

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +    describe('cannot-be-undefined: ', () => {
описание!!!

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +      const sutCanBe = new Cannotbe('phones', true, { isArray: true }, 'dto', FieldValidatorFixtures.phoneAttrsValidatorMap);
`sutCanBe = new Cannotbe` ???

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +          ],
хех, а тут ошибка правильно оформилась

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +        const result = sutCanBe.validate(1);
не массив валидного объекта

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +          { number: '+7-555-879-11-02', type: 'home', noOutField: 'invalid info' },
о, тут классно, не валидное значение близкое к ошибке которое может быть.

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +      const result = sut.validate(12);
объект, но не массив

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +    describe('can-be-undefined', () => {
исправь на нормальное описание, делайте сразу не откладывая, тогда не будут уходить в код ревью такие досадные ошибки

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +      const sutCanBe = new Cannotbe('phones', false, { isArray: true }, 'dto', FieldValidatorFixtures.phoneAttrsValidatorMap);
const sutCanBe = new Cannotbe ???

2023-10-05 13:41 UTC, NurGeo commented on tests/domain/validator/field/field-validatorArray.test.ts
> +          { number: '+7-777-287-81-82', type: 1, noOutField: 'empty info' },
1 поменять

2023-10-06 07:10 UTC, xHetso commented on tests/domain/validator/field/field-validatorArray.test.ts
> +        },
Думаю должно быть так, потому что 2 roles считаю лишним
test(' провал, один из элементов в массиве не валидно', () => {
      const roles = ['admin', 'staffManager', 'officeChieff', 'saleManager'];
      const sut = new LiteralFieldValidator('roles', true, { isArray: true }, 'string', [new StringChoiceValidationRule(roles)]);
      const res = sut.validate(['admin', 'officeChieff ']);
      expect(res.isFailure()).toBe(true);
      expect(res.value).toEqual({
        roles: {
          1: {
                hint: {
                  choices: [
                    'admin',
                    'staffManager',
                    'officeChieff',
                    'saleManager',
                  ],
                },
                text: 'Значение должно быть одним из значений списка',
          },
        },
      });
    });

2023-10-17 06:11 UTC, closed without merging