Реализованы тесты validate-rules min/max-number
NurGeo/rilata2 pull request #2
Opened 2023-09-07 19:43 UTC by FredSteady23

2023-09-08 05:38 UTC, NurGeo requested changes

2023-09-08 05:38 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/boolean/boolean.v-rule.ts
> +export abstract class BooleanValidationRule extends ValidationRule<'validate', boolean> {
нужно удалить файл, он больше не нужен

2023-09-08 05:38 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/number/max-number.v-rule.test.ts
> +        for (let i = 1; i <= maxAllowedNumber; i+=1) {
на самом деле избыточно делать цикл из 32 итерации, можно обойтись одни, но если хочешь сложности то вот тебе задание.

Пуст будет цикл из трех итерации, а число для валидации генерируется рандомно от -32 до +32.

Это будет какждый раз проверять на различные числа и количество тестов не будет таким большим.

2023-09-08 05:38 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/number/max-number.v-rule.test.ts
> +    });
1. Допустим ты получил здесь не правильный тип. Посмотри какую ты ошибку отправил назад. Между прочим ты скорее всего не знаешь про это. Распечатай ответ валидации в консоли и посмотри что приходит в случае ошибки. Как получишь ответ, скажи мне отдельно обсудим.
А все к тому, что этот тестовый случай не нужно проверять.
2. Расскажи мне что происходит внутри твоего forEach...
3. Не хватает еще двух тестовых случаев

Как прочитаешь этот коммент, обсуди ее со мной.

2023-09-08 05:38 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/number/min-number.v-rule.test.ts
> +describe('Number must be greater than or equal to', () => {
замечания те же что и файлом выше.

2023-09-10 08:40 UTC, closed without merging

2023-09-10 08:40 UTC, FredSteady23 commented
удален