Реализовал тесты для field-validator проверки на нулевое значение, тип данных, значении на соответствие правил
NurGeo/rilata2 pull request #21
Opened 2023-09-27 10:42 UTC by xHetso

2023-09-27 12:32 UTC, Renatter commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +      expect(result.isSuccess()).toBe(false);
Тут должен быть expect(result.isFailure()).toBe(true); так как test должен вернуть ошибку

2023-09-27 12:32 UTC, Renatter commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +      expect(result.isSuccess()).toBe(false);
тут тоже

2023-09-28 06:02 UTC, xHetso commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +      expect(result.isSuccess()).toBe(false);
Пофиксил

2023-09-28 06:02 UTC, xHetso commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +      expect(result.isSuccess()).toBe(false);
Пофиксил

2023-09-28 07:29 UTC, NurGeo requested changes
походу ты не понял что тебе надо тестировать).
После митинг все еще посидим.

2023-09-28 07:29 UTC, NurGeo commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +            text: "Значение не должно быть undefined или null",
"Значение не должно быть undefined или null"

Как думаешь, такое сообщение пользователю на форме нормально? Как то слишком технически написано.
Мне кажется надо изменить ее на что то вроде. "Значение не может быть пустым".

2023-09-28 07:29 UTC, NurGeo commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +            text: "Значение не должно быть undefined или null",
Хорошо бы поставить тикет и просмотреть все рулы на тексты на адеквватность с точки зрения пользователя.

2023-09-28 07:29 UTC, NurGeo commented on tests/domain/validator/field/field-validator-nullable.test.ts
> +  test('fail, passed as undefined or null parameter', () => {
тебе не надо тестировать валидаторы с фикстур, тебе надо тестировать сам код fieldValidator-а. Как приступишь к этому комменту спросишь меня.

2023-09-29 19:18 UTC, KLeBerLacky approved these changes

2023-10-03 11:24 UTC, closed without merging