Сделал рулы и тесты, ещё удалил не нужные рулы
NurGeo/rilata2 pull request #23
Opened 2023-09-29 06:38 UTC by KLeBerLacky

удалил booleanRule и equalDay потому что его можно реализовать в range-data

2023-09-29 12:02 UTC, Renatter commented on tests/domain/validator/rules/validate-rules/number/positive-number.v-rule.test.ts
> +    const sut = new PositiveNumberValidationRule();
можно 1 раз написать const sut = new PositiveNumberValidationRule(); для всех тестов  после describe() ;
**если у  PositiveNumberValidationRule(); нету аргумента**

2023-10-03 09:28 UTC, NurGeo requested changes

2023-10-03 09:28 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/number/positive-number.v-rule.test.ts
> +        text: 'Число должно быть положительным {{number}}',
то что в `text` покажется пользователю, т.е. "Число должно быть положительным 0"
Все нормально с текстом?

2023-10-03 09:28 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.test.ts
> +    });
допустим создали мы правило с `onlyChars='omb'`;
1. что мы должны получить как результат валидации в случае получиния следуюющих значений:
`'mom', 'bom', 'oms', 'bomb', 'bombs', 'dom', 'om', 'mo', 'bom mod', 'ooooo', 'mmo'`?
2. используй некоторые из приведенных тестовых случаев для тестов.

2023-10-03 09:28 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.test.ts
> +    });
1. по коду самого rule, ты или не правильно понял задачу или неправильно реализовал
2. твои тестовые кейсы не дают понимание для чего и как нужно использовать данный rule.

2023-10-09 08:59 UTC, closed without merging