Literal field validator tests
NurGeo/rilata2 pull request #26
Opened 2023-10-03 10:49 UTC by xHetso

2023-10-04 09:36 UTC, NurGeo requested changes
ближе к концу перестал смотреть, так как замечания одинаковые.
1. Явно пренережительное отношение к описаниям. Названия скоупов или тестов одинаковые. Это говорит о:
    1. не хочу думать об описании это скучно
    2. описание это неважно, все равно никто их не читает
2. часто есть скоуп который имеет только один тест, непонятно зачем он добавлен, описание тоже стандартное.

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +    test('провал, пришло не валидное значение для нескольких правил',()=>{
тестовое описание и сам тест не соответствуют друг другу.

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +    test('провал, пришло не валидное значение для нескольких правил',()=>{
такое же описание как и выше, непонятно что тестируется,

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('cannot-be-undefined, can-be-null',()=>{
измени описание скоупа на: `значение обязательно, но null валидное значение`

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +    test('успех, пришло null',()=>{
1. как у тебя согласуется описание теста и тело теста где валидация заканчивается провалом?
2. давайте договоримся, что успешные тестовые случаи мы пишем первыми.

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('cannot-be-undefined, can-be-null',()=>{
соответственно, как нужно сконфигурировать валидатор, чтобы тестировать случаи описанные для скоупа?

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('isNotArray_tests, isRequired_tests', () => {
`isNotArray_tests, isRequired_tests` нужно переписать используя нормальный язык. Как думаешь какие тесты находится в данном тестовом скоупе?

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('isNotArray_tests, isRequired_tests', () => {
описание скоупа вообще не соответствует тому что внутри.

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +      describe('Валидированная значение обязательна', () => {
этот скоуп непонятно для чего добавлен

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +        test('Успех, на валидацию пришло явное значение', () => {
описание теста вообще не говорит о чем тест и не связан с ним.

2023-10-04 09:36 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +    ];
так как у тебя один и тот же тип 'number', то двумерный массив излишен. можено `const values = [-Infinity, Infinity];`

2023-10-04 11:55 UTC, FredSteady23 approved these changes

2023-10-05 10:20 UTC, KLeBerLacky approved these changes

2023-10-11 06:01 UTC, NurGeo approved these changes

2023-10-12 11:15 UTC, NurGeo approved these changes

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('Получаем Infinity и NaN', () => {
измени на `Infinity и NaN по умолчанию не валидны для числовых значений"`

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  test('Провал, пришло пустая строка', () => {
Успех, пустая строка для не обязательного строкового валидатора считается валидным

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  test('Провал, пришло пустая строка', () => {
Провал, пустая строка для не обязательного не строкового валидатора считается не валидным

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +    const sut = new LiteralFieldValidator('fieldName', false, { isArray: false }, 'string', [new MaxCharsCountValidationRule(8), new UUIDFormatValidationRule()]);
правила бы более менее подходящие друг другу. Например max, no-space.

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  test('Провал, пришло не валидное значение для нескольких правил', () => {
чем это проверка отличается от верхнего?

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  test('Провал, пришло не валидное значение для нескольких правил', () => {
проверяйте тестовыми случаями

2023-10-12 11:15 UTC, NurGeo commented on tests/domain/validator/field/literal-field-validator.test.ts
> +  describe('Значение не может быть undefined', () => {
Значение не может быть undefined, но null допустимо

2023-10-12 11:20 UTC, merged