Реализованы тесты dto-field
NurGeo/rilata2 pull request #29
Opened 2023-10-05 10:54 UTC by FredSteady23

2023-10-05 12:32 UTC, Renatter commented on tests/domain/validator/field/dto-field-validator.test.ts
> +      describe('Cannot-be-undefined and can-be-null tests', () => {
тут должен быть descirbe('can-be-undefined, cannot-be-null') (_отпечатка  Нурболата_)
Нужно изменить код так, чтобы undefined был валидным значением, а null - нет.

2023-10-05 12:32 UTC, Renatter commented on tests/domain/validator/field/dto-field-validator.test.ts
> +          { number: '+7-555-879-11-02', type: 'work', noOutField: 'info' },
Будет лучше, если объекты будут разными.

2023-10-05 12:32 UTC, Renatter commented on tests/domain/validator/field/dto-field-validator.test.ts
> +      describe('Cannot-be-undefined and can-be-null test', () => {
тут должен быть descirbe('can-be-undefined, cannot-be-null')
Нужно изменить код так, чтобы undefined был валидным значением, а null - нет.

2023-10-06 07:16 UTC, xHetso requested changes

2023-10-09 11:38 UTC, xHetso requested changes

2023-10-09 11:38 UTC, xHetso commented on tests/domain/validator/field/dto-field-validator.test.ts
> +            },
Работает ли ошибка корректно?

2023-10-09 11:38 UTC, xHetso commented on tests/domain/validator/field/dto-field-validator.test.ts
> +          });
тут тоже

2023-10-09 11:38 UTC, xHetso commented on tests/domain/validator/field/dto-field-validator.test.ts
> +              },
тут тоже

2023-10-12 11:22 UTC, merged