Validate rule update
NurGeo/rilata2 pull request #30
Opened 2023-10-09 10:08 UTC by KLeBerLacky

2023-10-11 06:49 UTC, Renatter commented on tests/domain/validator/rules/validate-rules/number/positive-number.v-rule.test.ts
> +  test('success, resulting value is infinity', () => {
В ветке  move-from-rilata  есть готовые  рулы  для infinity и NaN. Можно запушать его и просмотреть полученные результаты.

2023-10-11 08:08 UTC, FredSteady23 commented on tests/domain/validator/rules/validate-rules/string/text-strict-equal.v-rule.test.ts
> +
Проверь несколько случаев когда есть тире или regex

2023-10-11 08:08 UTC, FredSteady23 commented on tests/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.test.ts
> +    const result = sut.validate(946800000000); // 2000, 0, 2, 12, 0, 0
Комменты не должны быть в код ревью и желательно их убрать

2023-10-11 08:08 UTC, FredSteady23 commented on src/domain/validator/rules/validate-rules/string/no-contained-chars.ts
> +    // eslint-disable-next-line no-restricted-syntax
Комменты не должны быть в код ревью

2023-10-11 08:08 UTC, FredSteady23 commented on src/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.ts
> +  private latinic = /^[ a-z0-9]+$/i;
Не должно быть символов или чисел так как мы проверяем на латиницу или кириллицу

2023-10-12 06:56 UTC, xHetso approved these changes
названии веток вроде пишем в формате kebab-case

2023-10-12 06:56 UTC, xHetso commented on src/domain/validator/rules/validate-rules/string/contained-only-chars.ts
> +      if (!this.onlyChars.includes(char)) {
Комментарий лучше думаю удалить

2023-10-12 06:56 UTC, xHetso commented on src/domain/validator/rules/validate-rules/string/no-contained-chars.ts
> +    // eslint-disable-next-line no-restricted-syntax
тут тоже коммент лучше удалить

2023-10-12 06:56 UTC, xHetso commented on tests/domain/validator/rules/validate-rules/string/text-strict-equal.v-rule.test.ts
> +describe('String must not be equal to value {{strictString}}', () => {
Описание в describe не совсем соответствует, describe('TextStrictEqualValidationRule Tests - String Equality Checks', () => { думаю было бы по лучше

2023-10-12 07:08 UTC, FredSteady23 approved these changes

2023-10-12 07:09 UTC, Renatter approved these changes

2023-10-12 10:50 UTC, NurGeo requested changes

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.test.ts
> +
нука сделай мне еще один тест с `Nurболат`. Чувствую я что получим ответ что это валидно.

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.test.ts
> +
если пройдет, то скажите мне пожалуйста, а почему ваш тест с `' English or Русский '` не сработал

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.ts
> +import { ValidationRuleAnswer } from '../../types';
имя файла должно заканчиваться на `.v-rule.ts`, посмотреть для всех файлов

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.ts
> +  requirement = 'В строке может быть только латиница и кирилица';
`'В строке может быть только латиница и кирилица'` -> `'Строка может содержать слова только на латинице или на кирилице. Нельзя их мешать.'`

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/string/text-strict-equal.v-rule.ts
> +  requirement = 'Значение должно быть {{strictString}}';
'Строка должна быть строго равна "{{strictString}}"'

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/string/text-strict-equal.v-rule.ts
> +  requirement = 'Значение должно быть {{strictString}}';
как ты думаешь, на что заменится `{{strictString}}`

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/timestamp/max-data.v-rule.ts
> +    return value < this.maxDateAsTimestamp
равное значение тоже можно считать допустимым.

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/timestamp/min-data.v-rule.ts
> +    return value > this.minDateAsTimestamp
равное значение тоже можно считать допустимым.

2023-10-12 10:50 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.ts
> +    return value > this.minRangeData && value < this.maxRangeData
равные значения тоже можно считать допустимым

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +    const sut = new ContainedOnlyCharsValidationRule('572741945712987');
`new ContainedOnlyCharsValidationRule('572741945712987')` -> `'0123456789'`

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value', () => {
еще успешный тестовый случай с `validate('b')`

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value', () => {
и не успешны `validate('s')`

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-chars.v-rule.test.ts
> +    const result = sut.validate('petrop#!!076@gmail.com');
сделай только одну причину для провала теста

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-chars.v-rule.test.ts
> +
должны быть тестовые случаи с причиной провала в начале, середине и конце строки.

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-spaсe.v-rule.test.ts
> +    const result = sut.validate('string\nWithTab');
`string\nWithTab`  -> `string${String.fromCharCode(10)}WithNewLine` так будет надежнее

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-spaсe.v-rule.test.ts
> +  test('failed, string contains tab spaces', () => {
еще тестовый случай с вертикальной табуляцией, код=11.

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.test.ts
> +    const result = sut.validate('1234567890');
лучше бы что то вроде `validate('string with 1 digit symbol')`

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/only-latinic-or-cyrillic-chars.test.ts
> +    const result = sut.validate('!"№;%:?*()');
опять же тест должен иметь только одну причину для провала.

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/text-strict-equal.v-rule.test.ts
> +    const result = sut.validate('bbbaaa');
лучше бы `'Aaabbb'`, это даст лучший тестовый случай чем явно несовместимое `'bbbaaa'`

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.test.ts
> +    expect(result).toEqual({
почему то коментарий Сагындыка помечен как "Разрешенный", но комменты почему то стоят еще.

2023-10-12 10:50 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.test.ts
> +    const result = sut.validate(946800000000); // 2000, 0, 2, 12, 0, 0
Читается ли код и что она делает лучше если написать так?
```js
const minDate = new Date('2000-01-01T15:00');
const maxDate = new Date('2000-01-01T15:12');
...

const result = sut.validate(new Date('2000-01-01T15:05').getTime())
```

2023-10-18 08:32 UTC, NurGeo approved these changes

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value', () => {
тестовый случай: 'успех, допускается несколько раз испльзовать один символ'

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value2', () => {
успех, можно успользовать только один символ много раз

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value', () => {
успех, все символы допустимы

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('success, string equal value2', () => {
успех, только один валидный символ

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('failure, string is not equal value', () => {
провал, только один не валидный символ

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +    const sut = new ContainedOnlyCharsValidationRule('b');
в конструктор также ('omb')

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +    const sut = new ContainedOnlyCharsValidationRule('s');
в конструктор также ('omb');
validate('s');

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('failure, string is not equal value', () => {
провал, переданный в конструктор required успешно передается в ошибку.

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/contained-only-chars.v-rule.test.ts
> +  test('failure, string is not equal value', () => {
провал, передана валидная строка с одним невалидным символом

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-chars.v-rule.test.ts
> +  test('failure, string contains invalid characters', () => {
провал, в ошибку успешно передается текст переданный в конструктор

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/no-contained-spaсe.v-rule.test.ts
> +    const result = sut.validate(`string${String.fromCharCode(11)}WithNewLine`);
`string${String.fromCharCode(11)}WithVerticalTab`

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.test.ts
> +    const result = sut.validate(new Date('1999-01-02T12:00').getTime());
Вот ты дату задвинул, сделай на пять минут раньше: `'1999-01-02T11:55'`

2023-10-18 08:32 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/timestamp/range-data.v-rule.test.ts
> +    const result = sut.validate(new Date('2020-01-02T12:00').getTime());
на пять минут позже

2023-10-18 10:57 UTC, merged