Validate number rules min/max
NurGeo/rilata2 pull request #6
Opened 2023-09-12 13:35 UTC by FredSteady23

2023-09-14 09:53 UTC, NurGeo requested changes

2023-09-14 09:53 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/number/range-number.v-rule.test.ts
> +  test('success, the resulting value in a range of numbers', () => {
нужны дополнительные тестовые случаи.

2023-09-14 11:04 UTC, Renatter approved these changes

2023-09-15 10:19 UTC, xHetso approved these changes

2023-09-18 07:54 UTC, merged